### ISSUE TITLE
ImportError: cannot import name 'trapz' from 'scipy.integrate' with scipy pre-release

### ISSUE THREAD

**Issue by Zethson** [CamDavidsonPilon/lifelines#1618]
> from lifelines import (
> /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/lifelines/__init__.py:4: in <module>
>     from lifelines.fitters.weibull_fitter import WeibullFitter
> /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/lifelines/fitters/__init__.py:21: in <module>
>     from scipy.integrate import trapz
> E   ImportError: cannot import name 'trapz' from 'scipy.integrate' (/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/scipy/integrate/__init__.py)

with the scipy pre-release version

scipy.integrate.trapz, scipy.integrate.cumtrapz, and scipy.integrate.simps have been deprecated in favour of [scipy.integrate.trapezoid](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.trapezoid.html#scipy.integrate.trapezoid), [scipy.integrate.cumulative_trapezoid](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.cumulative_trapezoid.html#scipy.integrate.cumulative_trapezoid), and [scipy.integrate.simpson](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.simpson.html#scipy.integrate.simpson) respectively and will be removed in SciPy 1.14.

**Comment by mariosyndena** [comment]
encountered the same issue: works with scipy 1.13.1, but not with scipy 1.14. plz update dependencies or add support for 1.14.
